alias ansible_start='source ~/.ansible-venv/bin/activate'
alias lt='ls --human-readable --size -1 -S --classify'
alias clip='xclip -se c'
alias updistrodeb='apt-get update && apt-get upgrade -yq && apt-get autoclean && apt-get autoremove'
alias updistro='zypper ref && zypper up && zypper clear'
alias k='kubectl'
alias t='terraform'
alias kderestart='killall plasmashell && kstart plasmashell &'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias dotfiles='/usr/bin/git --git-dir=/home/tbs/.dotfiles/ --work-tree=/home/tbs'
alias dotfiles='/usr/bin/git --git-dir=/home/tbs/.dotfiles/ --work-tree=/home/tbs'
